### ISSUE TITLE
Discussion: Purpose and scope of go-p2pd

### ISSUE THREAD

**Issue by MikeFair** [paralin/go-p2pd#1]
Forgive using the Issue for a question, but I'd like to get a grip on how I might make use of this daemon?

For example, if I'm writing an application and I'd like to "hook in" to the libp2p distributed network; what's the conceptual procedure here?

I can see that your daemon created a libp2p node it named test, and got it listening on 4001, and I can see that if I connected my app to http://127.0.0.1:4001/ I'd be talking to the daemon, but what happend next?

**Comment by paralin** [comment]
Sorry for not seeing this issue.

The idea is to make it a central connection router and transport registry for a device or set of processes. 

There has only been a minimal amount of effort put into the implementation so far, so this is by and large a plan and not a working implementation yet.

If you'd like to help implement, it, I'd love for more community interaction on this.

**Comment by paralin** [comment]
I think to answer your question more:

The idea has evolved a bit. I think now the best approach is to implement the mechanisms for loading transport plugins, to add KCP or uTP or whatnot. This is something the IPFS developers also want in IPFS. 

This plugin registry could be used other places as well, but this is a nice testbed and use case for it.

This implementation will basically function like:

 - Create one or more Node that has an identity (peer identity) and persistent state
 - Load TransportPlugin and attach to Node to enable listening on more multiaddrs (like /udp/kcp/)
 - Peers on the local device can connect over various efficient inter-process-communication transports to the daemon, just like any other p2p node, and then use the circuit feature of libp2p to do a 1 hop jump to reach the rest of the network.

One of the goals of this project is to use as few file descriptors as possible for p2p connectivity, part of that is having only one node interacting with the network via connections. It's a broadcast architecture.

This is not so far away from the current implementation in this repo.

cc @whyrusleeping @diasdavid

**Comment by paralin** [comment]
I think it might actually have diminishing returns to centralize this way... At the end of the day, it just requires multiple copies before sending data out.

**Comment by MikeFair** [comment]
FWIW, I think this is an absolutely awesome direction to go.
The main thing I'd want to see is PHY transport plugins at this layer
(think Bluetooth and LoRA for mobile/IOT), then let IPFS do the higher
protocol transport plugins.

The "pattern" I see is each device having a device peer id; and all the
apps/services having service peer ids.
The devices can then all swarm to discover each other in a project like
this, providing the routing, status, and perhaps even caching to other
local p2p instances.

There's currently no real mechanism for PubSub Channel Discovery or Direct
Stream connections; a project like this can provide that piece.



On Fri, Feb 16, 2018 at 4:30 AM, Christian Stewart <notifications@github.com

**Comment by paralin** [comment]
@MikeFair See p2p in libp2p and in ipfs. For channel discovery and direct connections there are some other implementations in the works. go-p2pd would provide the "Device Switch" part.

**Comment by paralin** [comment]
It seems clear to me that peer tracking and routing decisions, as well as transport loading / control, ought to be deduplicated at the device level. I think this is the purpose of this package.

cc @Stebalien
